app = "noticocacola"
primary_region = "gru"

[build]
  builder = "paketobuildpacks/builder:base"

[processes]
  worker = "python check_stock.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256